// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://hkw5m5bzjnas3iy55rofoibh2a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    Auth: {
        region: 'us-east-1',
        userPoolId: 'us-east-1_B78sn82ah',
        userPoolWebClientId: '7nca7db89qqeddmt2rh90587c5',
    }
};


export default awsmobile;
